// Generated by CoffeeScript 1.3.3
(function() {

  define(['underscore'], function(_) {
    return _.templateSettings = {
      interpolate: /\{\{(.+?)\}\}/g,
      evaluate: /\{\%(.+?)\%\}/g
    };
  });

}).call(this);
