// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'text!templates/index.html'], function($, _, Backbone, template) {
    var IndexView;
    return IndexView = (function(_super) {

      __extends(IndexView, _super);

      function IndexView() {
        return IndexView.__super__.constructor.apply(this, arguments);
      }

      IndexView.prototype.template = _.template(template);

      IndexView.prototype.title = "Test Application";

      IndexView.prototype.events = {
        "click a": "navigate"
      };

      IndexView.prototype.render = function() {
        document.title = this.title;
        this.$el.html(this.template({
          title: this.title
        }));
        return this;
      };

      IndexView.prototype.navigate = function(e) {
        if (e != null) {
          e.preventDefault();
        }
        return Backbone.history.navigate($(e.currentTarget).attr('href'), true);
      };

      return IndexView;

    })(Backbone.View);
  });

}).call(this);
